version: '3.8'

services:
  web:
    build:
      context: ./sito
      dockerfile: Dockerfile
    command: gunicorn sito.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.dev
  
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web