# Generated by Django 4.1.7 on 2023-04-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posizione', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'sezioni',
                'ordering': ['posizione'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_immagine', models.ImageField(blank=True, null=True, upload_to='')),
                ('ruolo', models.CharField(choices=[('immagine_profilo', 'about'), ('foto_portfolio', 'portfolio')], max_length=100, null=True)),
                ('posizione', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default='1', null=True)),
                ('sezione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.sezione')),
            ],
            options={
                'ordering': ['posizione'],
            },
        ),
    ]
