# Generated by Django 4.1.7 on 2023-05-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='ruolo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
