# Generated by Django 4.1.7 on 2023-05-02 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_photo_ruolo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='ruolo',
            new_name='immagine_profilo',
        ),
    ]
