# Generated by Django 2.2.12 on 2021-04-24 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['posizione']},
        ),
    ]
