# Generated by Django 3.1.7 on 2021-10-03 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sezione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posizione', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'sezioni',
                'ordering': ['posizione'],
            },
        ),
        migrations.AlterField(
            model_name='photo',
            name='posizione',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='ruolo',
            field=models.CharField(choices=[('immagine_profilo', 'about'), ('foto_portfolio', 'portfolio')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='sezione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sezione'),
        ),
    ]
