# Generated by Django 3.2.7 on 2021-09-23 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210923_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sezione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posizione', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'sezioni',
                'ordering': ['posizione'],
            },
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.AddField(
            model_name='photo',
            name='sezione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sezione'),
        ),
    ]
