# Generated by Django 3.2.7 on 2021-09-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210923_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='posizione',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='tag',
            field=models.CharField(choices=[('foto', 'Foto')], default='foto', max_length=20),
        ),
    ]
