# Generated by Django 3.2.7 on 2021-09-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210924_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='posizione',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
