# Generated by Django 3.2 on 2021-10-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211003_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['posizione']},
        ),
        migrations.AlterField(
            model_name='photo',
            name='posizione',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default='1', null=True),
        ),
    ]
